export const projects = [
  {
    slug: "milan",
    description: "A portfolio that gives creative work room to speak.",
    load: () => import("@/content/projects/milan.mdx"),
    title: "Milan",
    category: "Creative studio website",
    image: "/projects/og-milan.webp",
    imageAlt: "Milan: ‘Bespoke websites that WOW!’ above a reflective silver 3D form on a black background.",
    previewImage: "/projects/screenshot-milanco-v2.webp",
    coverPositionY: 0.5,
    width: 952,
    height: 600,
    liveUrl: "https://milanco.ca",
  },
  {
    slug: "joseph-law",
    description: "A clear route from legal information to contact.",
    load: () => import("@/content/projects/joseph-law.mdx"),
    coverPositionY: 0.35,
    title: "Joseph Law",
    category: "Law firm website",
    image: "/projects/og-josephlaw.webp",
    imageAlt: "Joseph Law: ‘For the times’ beneath a metallic monogram and glowing cube on a dark perspective grid.",
    previewImage: "/projects/screenshot-forthetimes-v3.webp",
    width: 1200,
    height: 630,
    liveUrl: "https://forthetimes.law",
  },
  {
    slug: "land-services-group",
    description: "A consistent digital presentation for a service brand.",
    load: () => import("@/content/projects/land-services-group.mdx"),
    coverPositionY: 0.5,
    title: "Land Services Group",
    category: "Brand website",
    image: "/projects/og-lsg.webp",
    imageAlt:
      "Land Services Group: a floating golden crystal above a dark green landscape, with white and gold lettering.",
    previewImage: "/projects/screenshot-lsg-v2.webp",
    width: 1200,
    height: 630,
    liveUrl: "https://landservicesgroup.ca",
  },
] as const;
